#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
This script is used to process the interaction log files.
It will produce consistent formatting, from which information
can be extracted to compute the bias metrics. 

Created on Mon Jul 17 00:29:52 2017

Example of log download in terminal:
    curl -G -o raw_logs9.json https://pull.logentries.com/541b6268-09ef-4845-8353-0303f85bb788/hosts/59c44822-80c6-44fb-a256-39edb09264e7/bbf63d14-9f71-4299-ab62-b62947008ee3/ \-d start=-7600000 \-d format=json

@author: emilywall
"""

import bias_util
import os
from os import listdir
from os.path import isfile, join

# separate logs into files for each user with one log per line
def process_file_by_user(directory, in_file_name): 
    f_in = open(directory + in_file_name, 'r')
    print 'Processing ', in_file_name
    user_id = None
    f_out = None
    
    # write each separate set of logs to a different file per user
    num_nulls = 0
    num_lines_written = 0
    for line in f_in: 
        if 'LOG' in line:
            # get the important part of the log
            line = line.replace('\\', '')
            first_index = line.index('\'')
            second_index = line.index('\'', first_index + 1)
            line = line[first_index + 1 : second_index]

            # determine which user the log was generated by
            if ('"userId":null' in line): 
                num_nulls += 1
                continue
            ind_1 = line.index('"userId":"') + 10
            ind_2 = line.index('"', ind_1 + 1)
            current_id = line[ind_1 : ind_2]

            if (current_id == '1506460542091'):
                num_lines_written += 1

            # open the file for this user
            if (current_id != user_id):
                user_id = current_id
                if (f_out != None): 
                    f_out.close()
                f_out = open(directory + 'temp_' + user_id + '.json', 'a')
            f_out.write(line + '\n')

    print '** 1506460542091 lines written: ', num_lines_written
    num_lines_written = 0
    if (num_nulls > 0):
        print '  Interactions from "null" user:', num_nulls
    # close remaining open files
    if (f_out != None):
        f_out.close()
    f_in.close()
    
# format the list of logs into comma-separated json array
def process_to_json(in_directory, in_file_name, out_directory, out_file_name):
    f_in = open(in_directory + in_file_name, 'r')
    f_out = open(out_directory + out_file_name, 'w+')
    last_line = None # maintain last line for comma formatting 
    
    f_out.write('[')
    
    # first read in all of the lines
    all_lines = []
    for line in f_in:
        all_lines.append(line)
    
    # sort the lines by time stamp
    all_lines.sort(key = get_date)
        
    # write the lines to the file
    for line in all_lines:
        if (last_line != None): 
            f_out.write(last_line + ',\n')
        last_line = line.strip()
        
    # write the last line and close it
    f_out.write(last_line)
    f_out.write(']')
    f_out.close()
    f_in.close()
    
# get the date from the line
def get_date(line):
    first_index = line.index('"eventTimeStamp":"')
    second_index = line.index('"', first_index + 18)
    date = line[first_index + 18 : second_index]

    return date

# this block is for pre-processing
# process each exported set of logs from logentries and create separate subdirectories for each user
if __name__ == '__main__': 
    orig_log_files = all_files = [f for f in listdir(bias_util.directory) if ('.json' in f and isfile(join(bias_util.directory, f)))]
    subdirectories = ['logs', 'plots']
    plot_subdirectories = ['all', 'fixed', 'classification_v1', 'classification_v2', 'category_v1', 'category_v2']
    for i in range(0, len(orig_log_files)):
        process_file_by_user(bias_util.directory, orig_log_files[i])
    all_files = [f for f in listdir(bias_util.directory) if ('temp_' in f and isfile(join(bias_util.directory, f)))]
    for i in range(0, len(all_files)):
        user_id = all_files[i][5:].replace('.json', '')
        new_directory = bias_util.directory + 'user_' + user_id + '/'
        
        # create the subdirectory structure
        if not os.path.exists(new_directory):
            os.makedirs(new_directory)    
        for j in range(0, len(subdirectories)):
            if not os.path.exists(new_directory + subdirectories[j] + '/'):
                os.makedirs(new_directory + subdirectories[j] + '/')
        for j in range(0, len(plot_subdirectories)):
            if not os.path.exists(new_directory + 'plots/' + plot_subdirectories[j] + '/'):
                os.makedirs(new_directory + 'plots/' + plot_subdirectories[j] + '/')
                
        new_file_name = 'interactions_' + user_id + '.json'
        process_to_json(bias_util.directory, all_files[i], new_directory + 'logs/', new_file_name)
        os.remove(bias_util.directory + all_files[i]) # comment out this line to keep the temporary files for debugging purposes
        print 'Processed ', new_file_name